[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_report = ["Rings"]
solc = "0.8.19"
remappings = [
    "@thirdweb-dev/=node_modules/@thirdweb-dev/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "eas-contracts/=eas-contracts/",
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config